manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: yangdigi
      url-base: https://github.com/yangdigi
  projects:
    - name: zmk
      remote: zmkfirmware  # <-- 여기를 공식 ZMK 저장소로 변경했습니다.
      revision: main       # <-- 여기를 ZMK Studio를 지원하는 최신 버전으로 변경했습니다.
      import: app/west.yml
    - name: zmk-keyboards-klink
      remote: yangdigi
      revision: main
  self:
    path: config
