manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: yangdigi
      url-base: https://github.com/yangdigi
  projects:
    - name: zmk
      remote: yangdigi     # <-- 다시 yangdigi로 복구합니다.
      revision: v0.3       # <-- 버전도 커스텀 호환성이 맞는 v0.3으로 복구합니다.
      import: app/west.yml
    - name: zmk-keyboards-klink
      remote: yangdigi
      revision: main
  self:
    path: config
